---
pool:
  vmImage: 'ubuntu-latest'
  name: "Azure pipelines"

trigger: 
  - main

jobs:
  - job: software_installations
    displayName: openjdk11
    continueOnError: "false"
    steps:
      - task: Maven@4
        inputs:
          packagetype: 'mvn'
          version: latest

jobs:
  - job: Build_job
    displayName : springpet-clinic
    dependsOn: software_installations
    condition: succeeded()
    steps:
      - task: Maven@4
        inputs: 
          command: "mvn package"
          
  